const icon = {
  // 基础组件图标
  row: 'fluent:layout-row-two-16-regular',
  column: 'fluent:layout-column-two-split-right-16-regular',
  image: 'fluent:image-16-regular',
  video: 'fluent:video-clip-multiple-16-regular',
  text: 'fluent:text-bullet-list-square-edit-24-regular',
  swiper: 'fluent:app-recent-24-regular',
  blank: 'fluent:border-none-20-filled',
  canvas: 'fluent:draw-image-24-regular',
  h1: 'icon-park-outline:h1',
  h2: 'icon-park-outline:h2',
  h3: 'icon-park-outline:h3',
  text_md: 'solar:text-bold',
  ol: 'gravity-ui:list-ol',
  ul: 'gravity-ui:list-ul',
  high_block: 'fluent:calendar-week-start-24-regular',
  code: 'fluent:code-block-16-regular',
  workSquare: 'mingcute:mark-pen-line',

  // 平台图标
  allViewport: 'fluent:phone-desktop-24-regular',
  desktop: 'fluent:desktop-mac-32-regular',
  mobile: 'fluent:phone-16-regular',
  preview: 'icon-park-outline:preview-open',
  question: 'fluent:question-circle-12-regular',
  tips: 'fluent:info-24-regular',
  publish: 'iconamoon:cloud-yes',
  search: 'fluent:search-12-regular',
  block: 'fluent:app-folder-16-regular',
  blockActive: 'fluent:app-folder-16-filled',
  kit: 'fluent:layer-24-regular',
  kitActive: 'fluent:layer-24-filled',
  home: 'majesticons:home-line',
  homeActive: 'majesticons:home',
  package: 'ph:package-duotone',
  packageActive: 'ph:package-fill',
  user: 'ri:user-5-line',
  userActive: 'ri:user-5-fill',
  upload: 'fluent:arrow-upload-16-filled',
  expand: 'fluent:panel-right-expand-16-regular',
  copy: 'fluent:save-copy-24-regular',
  delete: 'fluent:delete-24-regular',
  drag: 'fluent:grid-dots-20-regular',
  dragBlank: 'fluent:breakout-room-20-regular',
  add: 'fluent:add-16-regular',
  subtract: 'fluent:subtract-16-regular',
  back: 'fluent:chevron-left-20-filled',
  save: 'fluent:save-16-regular',
  prod: 'vscode-icons:file-type-flareact',
  workSquareActive: 'mingcute:mark-pen-fill'
}

export default icon

export type ConfigIcon = keyof typeof icon
